/**
 * KisanSetu — Minimal Mock Data Structure
 * Provides realistic structural blueprints for development before FastAPI integration.
 */

const MOCK_CENTERS = [
  {
    id: "CTR-HR-01",
    centerId: "CTR-HR-01",
    name: "Karnal Central Procurement Center",
    district: "Karnal",
    state: "Haryana",
    address: "Near New Anaj Mandi, GT Road, Karnal, Haryana - 132001",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    acceptedCrops: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक वेईब्रिज", "किसान प्रतीक्षालय", "नमी मापक लैब", "ऑपरेटर सहायता"],
    dailyCapacityMT: 500,
    dailyCapacity: "500 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 12,
    estimatedWaitMinutes: 45,
    loadStatus: "low" // 'low' | 'medium' | 'high'
  },
  {
    id: "CTR-HR-02",
    centerId: "CTR-HR-02",
    name: "Ambala Grain Market Center",
    district: "Ambala",
    state: "Haryana",
    address: "Kalka Chowk Mandi Complex, Ambala City, Haryana - 134003",
    operatingHours: "08:30 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Paddy (Common)",
    commodities: ["Paddy (Common)", "Wheat (Grade A)", "Maize"],
    acceptedCrops: ["Paddy (Common)", "Wheat (Grade A)", "Maize"],
    facilities: ["डिजिटल टोकन", "वेईब्रिज लेन 1 & 2", "किसान शेड", "ऑपरेटर डेस्क"],
    dailyCapacityMT: 600,
    dailyCapacity: "600 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 28,
    estimatedWaitMinutes: 80,
    loadStatus: "medium"
  },
  {
    id: "CTR-HR-03",
    centerId: "CTR-HR-03",
    name: "Rohtak Central Procurement Center",
    district: "Rohtak",
    state: "Haryana",
    address: "Jhajjar Road Anaj Mandi Yard, Rohtak, Haryana - 124001",
    operatingHours: "09:00 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Mustard", "Bajra"],
    acceptedCrops: ["Wheat (Grade A)", "Mustard", "Bajra"],
    facilities: ["डिजिटल टोकन", "ऑटोमेटेड वेईब्रिज लेन 1-3", "किसान विश्राम गृह", "सॉइल व मॉइस्चर टेस्टिंग"],
    dailyCapacityMT: 700,
    dailyCapacity: "700 MT / दिन",
    slotDuration: "45 मिनट",
    currentQueueVehicles: 8,
    estimatedWaitMinutes: 25,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-04",
    centerId: "CTR-HR-04",
    name: "Jhajjar Anaj Mandi Center",
    district: "Jhajjar",
    state: "Haryana",
    address: "Rewari-Rohtak Bypass, Mandi Complex, Jhajjar, Haryana - 124103",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Mustard",
    commodities: ["Mustard", "Wheat (Grade A)", "Bajra"],
    acceptedCrops: ["Mustard", "Wheat (Grade A)", "Bajra"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक कांटा", "किसान प्रतीक्षालय", "नमी परीक्षण"],
    dailyCapacityMT: 550,
    dailyCapacity: "550 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 15,
    estimatedWaitMinutes: 40,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-05",
    centerId: "CTR-HR-05",
    name: "Sonipat Grain Yard Center",
    district: "Sonipat",
    state: "Haryana",
    address: "Old DC Road Mandi, Sonipat, Haryana - 131001",
    operatingHours: "08:30 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    acceptedCrops: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    facilities: ["डिजिटल टोकन", "डबल वेईब्रिज", "किसान शेड", "सीसीटीवी सुरक्षा"],
    dailyCapacityMT: 650,
    dailyCapacity: "650 MT / दिन",
    slotDuration: "45 मिनट",
    currentQueueVehicles: 34,
    estimatedWaitMinutes: 95,
    loadStatus: "high"
  },
  {
    id: "CTR-HR-06",
    centerId: "CTR-HR-06",
    name: "Panipat Agro Intake Terminal",
    district: "Panipat",
    state: "Haryana",
    address: "Barsat Road New Mandi, Panipat, Haryana - 132103",
    operatingHours: "08:00 AM – 06:00 PM (सोमवार से शनिवार)",
    commodity: "Paddy (Common)",
    commodities: ["Paddy (Common)", "Wheat (Grade A)", "Barley"],
    acceptedCrops: ["Paddy (Common)", "Wheat (Grade A)", "Barley"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक वेईब्रिज लेन 1-4", "लैब टेस्टिंग", "कैंटीन"],
    dailyCapacityMT: 800,
    dailyCapacity: "800 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 24,
    estimatedWaitMinutes: 65,
    loadStatus: "medium"
  },
  {
    id: "CTR-HR-07",
    centerId: "CTR-HR-07",
    name: "Hisar Mandi Hub",
    district: "Hisar",
    state: "Haryana",
    address: "Sirsa Road Anaj Mandi, Hisar, Haryana - 125001",
    operatingHours: "09:00 AM – 06:00 PM (सोमवार से शनिवार)",
    commodity: "Cotton",
    commodities: ["Cotton", "Wheat (Grade A)", "Mustard", "Gram"],
    acceptedCrops: ["Cotton", "Wheat (Grade A)", "Mustard", "Gram"],
    facilities: ["डिजिटल टोकन", "कपास ग्रेडिंग लैब", "हैवी वेईब्रिज", "विश्राम गृह"],
    dailyCapacityMT: 900,
    dailyCapacity: "900 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 18,
    estimatedWaitMinutes: 50,
    loadStatus: "medium"
  },
  {
    id: "CTR-HR-08",
    centerId: "CTR-HR-08",
    name: "Bhiwani Procurement Center",
    district: "Bhiwani",
    state: "Haryana",
    address: "Tosham Road Mandi Yard, Bhiwani, Haryana - 127021",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Bajra",
    commodities: ["Bajra", "Mustard", "Gram", "Wheat (Grade A)"],
    acceptedCrops: ["Bajra", "Mustard", "Gram", "Wheat (Grade A)"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक कांटा", "किसान सहायता केंद्र"],
    dailyCapacityMT: 500,
    dailyCapacity: "500 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 9,
    estimatedWaitMinutes: 30,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-09",
    centerId: "CTR-HR-09",
    name: "Jind Grain Depot",
    district: "Jind",
    state: "Haryana",
    address: "Safidon Road Grain Market, Jind, Haryana - 126102",
    operatingHours: "08:30 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    acceptedCrops: ["Wheat (Grade A)", "Paddy (Common)", "Mustard"],
    facilities: ["डिजिटल टोकन", "वेईब्रिज", "किसान प्रतीक्षालय", "नमी मापक उपकरण"],
    dailyCapacityMT: 600,
    dailyCapacity: "600 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 20,
    estimatedWaitMinutes: 60,
    loadStatus: "medium"
  },
  {
    id: "CTR-HR-10",
    centerId: "CTR-HR-10",
    name: "Rewari Krishi Mandi Center",
    district: "Rewari",
    state: "Haryana",
    address: "Bawal Road Anaj Mandi, Rewari, Haryana - 123401",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Mustard",
    commodities: ["Mustard", "Bajra", "Wheat (Grade A)"],
    acceptedCrops: ["Mustard", "Bajra", "Wheat (Grade A)"],
    facilities: ["डिजिटल टोकन", "सरसों ऑयल कंटेंट टेस्टिंग", "वेईब्रिज", "किसान शेड"],
    dailyCapacityMT: 520,
    dailyCapacity: "520 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 7,
    estimatedWaitMinutes: 20,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-11",
    centerId: "CTR-HR-11",
    name: "Sirsa Agro Yard",
    district: "Sirsa",
    state: "Haryana",
    address: "Barnala Road New Anaj Mandi, Sirsa, Haryana - 125055",
    operatingHours: "08:30 AM – 06:00 PM (सोमवार से शनिवार)",
    commodity: "Cotton",
    commodities: ["Cotton", "Wheat (Grade A)", "Paddy (Common)", "Gram"],
    acceptedCrops: ["Cotton", "Wheat (Grade A)", "Paddy (Common)", "Gram"],
    facilities: ["डिजिटल टोकन", "मल्टी-लेन वेईब्रिज", "कपास परीक्षण प्रयोगशाला", "किसान लॉज"],
    dailyCapacityMT: 850,
    dailyCapacity: "850 MT / दिन",
    slotDuration: "45 मिनट",
    currentQueueVehicles: 30,
    estimatedWaitMinutes: 85,
    loadStatus: "medium"
  },
  {
    id: "CTR-HR-12",
    centerId: "CTR-HR-12",
    name: "Kaithal Grain Market",
    district: "Kaithal",
    state: "Haryana",
    address: "Dhand Road Mandi Complex, Kaithal, Haryana - 136027",
    operatingHours: "09:00 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Paddy (Common)",
    commodities: ["Paddy (Common)", "Wheat (Grade A)"],
    acceptedCrops: ["Paddy (Common)", "Wheat (Grade A)"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक वेईब्रिज", "धान गुणवत्ता लैब"],
    dailyCapacityMT: 750,
    dailyCapacity: "750 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 16,
    estimatedWaitMinutes: 45,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-13",
    centerId: "CTR-HR-13",
    name: "Kurukshetra Procurement Center",
    district: "Kurukshetra",
    state: "Haryana",
    address: "Pipli Road Grain Market, Kurukshetra, Haryana - 136118",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Paddy (Common)", "Maize"],
    acceptedCrops: ["Wheat (Grade A)", "Paddy (Common)", "Maize"],
    facilities: ["डिजिटल टोकन", "वेईब्रिज", "किसान विश्राम गृह", "हेल्पडेस्क"],
    dailyCapacityMT: 620,
    dailyCapacity: "620 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 11,
    estimatedWaitMinutes: 35,
    loadStatus: "low"
  },
  {
    id: "CTR-HR-14",
    centerId: "CTR-HR-14",
    name: "Fatehabad Mandi Depot",
    district: "Fatehabad",
    state: "Haryana",
    address: "GT Road Mandi Yard, Fatehabad, Haryana - 125050",
    operatingHours: "09:00 AM – 05:30 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Cotton", "Paddy (Common)"],
    acceptedCrops: ["Wheat (Grade A)", "Cotton", "Paddy (Common)"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक कांटा", "ऑपरेटर डेस्क", "पेयजल सुविधा"],
    dailyCapacityMT: 580,
    dailyCapacity: "580 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 14,
    estimatedWaitMinutes: 40,
    loadStatus: "low"
  },
  {
    id: "CTR-MP-04",
    centerId: "CTR-MP-04",
    name: "Indore Regional Procurement Center",
    district: "Indore",
    state: "Madhya Pradesh",
    address: "Laxmibai Nagar Mandi Yard, Indore, Madhya Pradesh - 452006",
    operatingHours: "09:00 AM – 06:00 PM (सोमवार से शनिवार)",
    commodity: "Soybean",
    commodities: ["Soybean", "Wheat (Grade A)", "Gram"],
    acceptedCrops: ["Soybean", "Wheat (Grade A)", "Gram"],
    facilities: ["डिजिटल टोकन", "ऑटोमेटेड वेईब्रिज", "किसान विश्राम गृह", "सॉइल व मॉइस्चर टेस्टिंग"],
    dailyCapacityMT: 800,
    dailyCapacity: "800 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 48,
    estimatedWaitMinutes: 140,
    loadStatus: "high"
  },
  {
    id: "CTR-MP-02",
    centerId: "CTR-MP-02",
    name: "Bhopal Krishi Mandi Hub",
    district: "Bhopal",
    state: "Madhya Pradesh",
    address: "Karond Mandi By-Pass, Bhopal, Madhya Pradesh - 462038",
    operatingHours: "09:00 AM – 05:00 PM (सोमवार से शनिवार)",
    commodity: "Wheat (Grade A)",
    commodities: ["Wheat (Grade A)", "Soybean", "Maize"],
    acceptedCrops: ["Wheat (Grade A)", "Soybean", "Maize"],
    facilities: ["डिजिटल टोकन", "इलेक्ट्रॉनिक कांटा", "ऑपरेटर काउंटर", "किसान सहायता केंद्र"],
    dailyCapacityMT: 750,
    dailyCapacity: "750 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 16,
    estimatedWaitMinutes: 50,
    loadStatus: "low"
  },
  {
    id: "CTR-PB-01",
    centerId: "CTR-PB-01",
    name: "Patiala Focal Point Depot",
    district: "Patiala",
    state: "Punjab",
    address: "Sirhind Road Focal Point, Patiala, Punjab - 147004",
    operatingHours: "08:00 AM – 06:00 PM (सोमवार से शनिवार)",
    commodity: "Paddy (Common)",
    commodities: ["Paddy (Common)", "Wheat (Grade A)"],
    acceptedCrops: ["Paddy (Common)", "Wheat (Grade A)"],
    facilities: ["डिजिटल टोकन", "डबल वेईब्रिज", "विश्राम केंद्र", "हेल्पडेस्क"],
    dailyCapacityMT: 900,
    dailyCapacity: "900 MT / दिन",
    slotDuration: "60 मिनट",
    currentQueueVehicles: 35,
    estimatedWaitMinutes: 95,
    loadStatus: "medium"
  }
];

const MOCK_COMMODITIES = [
  {
    id: "COMM-WHEAT-A",
    name: "Wheat (Grade A)",
    nameEnglish: "Wheat",
    hindiName: "गेहूं (ग्रेड ए)",
    nameHindi: "गेहूं",
    category: "Cereal (रबी अनाज)",
    season: "Rabi (रबी)",
    unit: "QTL",
    demoRate: 2425, // Illustrative demo rate in INR (₹/QTL)
    mspPerQuintal: 2275, // Backward compatibility baseline
    moistureMaxPercent: 12.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-PADDY-COMM",
    name: "Paddy (Common)",
    nameEnglish: "Paddy",
    hindiName: "धान (सामान्य)",
    nameHindi: "धान",
    category: "Cereal (खरीफ अनाज)",
    season: "Kharif (खरीफ)",
    unit: "QTL",
    demoRate: 2320,
    mspPerQuintal: 2183,
    moistureMaxPercent: 17.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-MUSTARD",
    name: "Mustard",
    nameEnglish: "Mustard",
    hindiName: "सरसों",
    nameHindi: "सरसों",
    category: "Oilseed (तिलहन)",
    season: "Rabi (रबी)",
    unit: "QTL",
    demoRate: 5650,
    mspPerQuintal: 5650,
    moistureMaxPercent: 9.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-BAJRA",
    name: "Bajra",
    nameEnglish: "Bajra",
    hindiName: "बाजरा",
    nameHindi: "बाजरा",
    category: "Coarse Grain (मोटा अनाज)",
    season: "Kharif (खरीफ)",
    unit: "QTL",
    demoRate: 2625,
    mspPerQuintal: 2500,
    moistureMaxPercent: 12.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-COTTON",
    name: "Cotton",
    nameEnglish: "Cotton",
    hindiName: "कपास",
    nameHindi: "कपास",
    category: "Fiber (नकदी फसल)",
    season: "Kharif (खरीफ)",
    unit: "QTL",
    demoRate: 7122,
    mspPerQuintal: 6620,
    moistureMaxPercent: 8.5,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-MAIZE",
    name: "Maize",
    nameEnglish: "Maize",
    hindiName: "मक्का",
    nameHindi: "मक्का",
    category: "Cereal (मोटा अनाज)",
    season: "Kharif (खरीफ)",
    unit: "QTL",
    demoRate: 2225,
    mspPerQuintal: 2090,
    moistureMaxPercent: 14.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-BARLEY",
    name: "Barley",
    nameEnglish: "Barley",
    hindiName: "जौ",
    nameHindi: "जौ",
    category: "Cereal (रबी अनाज)",
    season: "Rabi (रबी)",
    unit: "QTL",
    demoRate: 1980,
    mspPerQuintal: 1850,
    moistureMaxPercent: 12.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-GRAM",
    name: "Gram",
    nameEnglish: "Gram",
    hindiName: "चना",
    nameHindi: "चना",
    category: "Pulse (दलहन)",
    season: "Rabi (रबी)",
    unit: "QTL",
    demoRate: 5440,
    mspPerQuintal: 5440,
    moistureMaxPercent: 10.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  },
  {
    id: "COMM-SOYBEAN",
    name: "Soybean",
    nameEnglish: "Soybean",
    hindiName: "सोयाबीन",
    nameHindi: "सोयाबीन",
    category: "Oilseed (तिलहन)",
    season: "Kharif (खरीफ)",
    unit: "QTL",
    demoRate: 4892,
    mspPerQuintal: 4892,
    moistureMaxPercent: 12.0,
    demoDisclaimer: "डेमो दर • Demo Rate (Illustrative)"
  }
];

const MOCK_SAMPLE_TOKEN = {
  tokenId: "KS-2026-HR01-0842",
  farmerName: "Rameshwar Singh",
  farmerPhone: "XXXXXX4512",
  centerId: "CTR-HR-01",
  commodityId: "COMM-WHEAT-A",
  scheduledDate: "2026-09-05",
  timeSlot: "10:00 AM - 11:30 AM",
  approximateWeightQuintals: 40,
  vehicleNumber: "HR-05-AB-1234",
  status: "CONFIRMED" // 'CONFIRMED' | 'IN_QUEUE' | 'WEIGHED' | 'COMPLETED' | 'CANCELLED'
};

// Export to window for vanilla JS browser usage
if (typeof window !== "undefined") {
  window.MOCK_CENTERS = MOCK_CENTERS;
  window.MOCK_COMMODITIES = MOCK_COMMODITIES;
  window.MOCK_SAMPLE_TOKEN = MOCK_SAMPLE_TOKEN;
  window.KisanMockData = {
    MOCK_CENTERS,
    MOCK_COMMODITIES,
    MOCK_SAMPLE_TOKEN
  };
}

